# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  output-file: output.txt
  artifact-file: the-file

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [17]

    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: $build.strategy.matrix.java-version
      
      - name: print java version to file
        run: java --version > $output-file
        
      - name: upload output-file
        uses: actions/upload-artifact@v3.1.2
        with:
          name: $artifact-file
          path: $output-file

  build2:
    runs-on: ubuntu-latest
    
    needs: build
    
    steps:
      - name: download output-file
        uses: actions/download-artifact@v1.0.4
        with:
          name: $artifact-file
          
      - name: print java version
        run: cat $artifact-file
    
