name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    steps:
      - uses: actions/checkout@v3

      - name: setup java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: ${{ matrix.java-version }}
      
      - name: print java version to file
        run: "java -version > output-file 2>&1"
        
      - name: upload output-file
        uses: actions/upload-artifact@v3.1.2
        with:
          name: "artifact-file-${{ matrix.java-version }}"
          path: output-file

  build2:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [8, 11, 17]

    needs: build
    
    steps:
      - name: download output-file
        uses: actions/download-artifact@v2.1.1
        with:
          name: "artifact-file-${{ matrix.java-version }}"
          
      - name: print java version
        run: "cat output-file"
    
